// <auto-generated />
namespace enrollmentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Notes1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notes1));
        
        string IMigrationMetadata.Id
        {
            get { return "201810140049041_Notes1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
